accounts/urls.py
from accounts.views import signupView
from django.urls import path
from .views import signupView , loginView ,logoutView

app_name = 'accounts'

urlpatterns = [
path('signup/',signupView,name='signupView'),
path('login/',loginView,name='loginView'),
path('logout/',logoutView,name='logoutView')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # to access us to the image url

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
path('',views.index,name="index"), # we use attribiute name for action's url in templates
path('blog/',views.text,name="text"),
path('homepage/', views.homePage,name='home'),
path('story/<int:pk>',views.storyTellerGeneric.as_view(),name='story_datail'),
path('story/',views.storyListsGeneric.as_view(),name='lists_of_stories'),
path('like/<id>',views.storyLike,name='storylike'),
path('unlike/<id>',views.storyUnlike,name='storyunlike'),


]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.db.models.fields import CharField, EmailField
from django.utils import timezone
from django.contrib.auth.models import User

#The name of each Field instance (Question , Choice) 
# You’ll use this value in your Python code, and your database will use it as the column name.

'''
each model is represented by a class that subclasses django.db.models.Model.
 Each model has a number of class variables, each of which represents a database field in the model.

Each field is represented by an instance of a Field class – e.g.,
 CharField for character fields and DateTimeField for datetimes.
  This tells Django what type of data each field holds.

'''
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    # ForeignKey. That tells Django each Choice is related to a single Question. 
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class information(models.Model):
    name = models.CharField(max_length=60)
    lastName = models.CharField(max_length=60)
    adress = models.TextField()
    email = models.EmailField(max_length=50)
    def __str__(self):
        return self.name 



class storyData(models.Model):
    title = models.CharField(max_length=60)
    story = models.TextField()
    date = models.DateField(auto_now_add=True)

    # ForeignKey is used for one to many relationship
    author = models.ForeignKey(User ,models.CASCADE,null=True,blank=True)
    # NULL AND BLANK IS FOR WHETER PREVIOS OBJECTS HAS AUTHOR ATRIBIUTE OR NOT .it's okay or not
    #CASCADE : When the referenced object is deleted, also delete the objects that have references


    image = models.ImageField(upload_to='%Y/%m/%d',null=True,blank=True) # this will save files into folders like (2021/05/19)
    # for many to many relationship
    # if there was two relationship in one model, you need to set a related-name
    likes = models.ManyToManyField(User,related_name='storyLike',blank=True) 


    def __str__(self):
        return self.title


    def getsnippet(self):
        return self.story[0:65] + ' .....'
    '''
1   Change your models (in models.py).
2   Run python manage.py makemigrations to create migrations for those changes
3   Run python manage.py migrate to apply those changes to the database. 
    '''

polls/forms.py
from django import forms
from django.forms.widgets import Textarea
class addStoryForm(forms.Form):
    title = forms.CharField(label='title',max_length=200)
    content = forms.CharField(label='content',widget=Textarea)
    image = forms.ImageField()

accounts/views.py
from django.http.response import HttpResponse
from django.shortcuts import render ,redirect
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm # for login
from django.contrib.auth import login ,logout


def signupView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user) # to login too afters signing up
            return HttpResponse('you have been signed up!!')


    form = UserCreationForm()
    return render(request,'accounts/signUp.html',{'form':form})

def loginView(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('/polls/blog')


    form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/accounts/login')

polls/views.py
from .models import information, storyData
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .forms import addStoryForm
from django.views import generic



#  In Django, web pages and other content are delivered by views.
#  Each view is represented by a Python function (or method, in the case of class-based views)

def index(request):
    data='<h3>This is a Heading</h3>'
    return HttpResponse(data)

# Create your Form
def text(request): 
    if request.method == "POST":
        form=addStoryForm(request.POST,request.FILES)
        if form.is_valid():
            title=form.cleaned_data['title']
            content=form.cleaned_data['content']
            image = form.cleaned_data['image']
            author=request.user
            
            blog=storyData.objects.create(title=title,story=content,author=author,image=image)
            blog.save()
           
            return HttpResponse('Created!')
    else:
        form=addStoryForm()
    arg={'form':form}
    return render(request,'polls/blog_page.html',arg)     
    



def detail(request,question_id):
    return HttpResponse(f'this is your questin {question_id}')
def result(request , question_id):
    return HttpResponse(f'this is the result {question_id}')

def vote(request, var):
    context={'var':var}
    return render(request,'polls/vote.html',context)

def homePage(request):
    inform = information.objects.all()
    arg={'inform':inform}
    return render(request , 'polls/home.html',arg)

# Generic view : build in function to make it simple and easier
# in order to use GV you need to use class which heritate form django.views.generic.
# and in url you have to use ClassName.as_view()
 
class storyListsGeneric(generic.ListView):
    template_name='polls/listsofstories.html'
    context_object_name='lists'

    def get_queryset(self):
        return storyData.objects.all() 



# def storyLists(request):
#     data = storyData.objects.all()
#     arg = {'lists':data}
#     return render(request,'listsofstories.html',arg)


# def storyteller(request,storyid):
#     data = storyData.objects.get(id=storyid) # get info from model
#     arg={'story':data}
#     return render(request,'story.html',arg )

class storyTellerGeneric(generic.DetailView):
    template_name = 'polls/story.html'
    model = storyData # django make all letters lower , use this in tamplate tags
    



def storyLike(request,id):
    story = storyData.objects.get(id=id)
    user = request.user
    if user.is_authenticated:

        if user in story.likes.all():
            return HttpResponse('you have already liked this story')
        else:
            story.likes.add(user)
            return redirect('polls:story_datail',id)
    else:
        return HttpResponse('you are not allow to like this story')


def storyUnlike(request,id):
    story = storyData.objects.get(id=id)
    user = request.user
    if user.is_authenticated:
        if user in story.likes.all():
            story.likes.remove(user)
            return redirect('polls:story_datail',id)
        else:
            return HttpResponse('you have never liked this')
    else:
        return HttpResponse('you are not allow to like this')

accounts/templates/accounts/login.html
{%extends 'base.html'%}
{%block title%}Login{%endblock title%}

{%block content%}
<h1>LOGIN</h1> 
<form action="" method="POST">
{%csrf_token%}
{{form}}
<button type="submit">LOGIN</button>
</form>

{%endblock content%}

accounts/templates/accounts/signUp.html
{%extends 'base.html'%}

{%block title%}Sign Up{%endblock title%}

{%block content%}
<h1>SIGN UP</h1> 
<form action="" method="POST">
{%csrf_token%}
{{form}}
<button type="submit">SIGN UP</button>
</form>

{%endblock content%}

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%load static%}
    {#<link rel="stylesheet" href="{% static 'polls/style.css' %}">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<title>{%block title%}{%endblock title%}</title>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'polls:home'%}">HOME</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'polls:lists_of_stories'%}">Stories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:loginView'%}">login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:signupView'%}">sign up</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              MORE
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{%url 'polls:text'%}">Add Story</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>




</head>
<body>

    {%block content%}{%endblock content%}
    
    {%block content2%}{%endblock content2%}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
<footer class="footer_m">
created by : eamirh@outlook.com


</footer>
</html>

polls/templates/polls/blog_page.html
{%extends 'base.html'%}
{%block title%}Add Story{%endblock title%}

{%block content%}
  {%if user.is_authenticated%}

<form enctype="multipart/form-data" action="{%url 'polls:text'%}" method="POST">

    {% csrf_token %}
    
    {{form.title}}
    <br>
    {{form.content}}
    <br>
    {{form.image}}
<button type="submit">Send</button>

</form>
<form action="{%url 'polls:lists_of_stories'%}" method="GET">
    {% csrf_token %}
    <button type="submit"> show stories</button>  
</form>
{%else%}
<h1 style="color: brown;">You Need To Login</h1>
{%endif%}


{%endblock content%}
  

polls/templates/polls/home.html
{%extends 'base.html'%}
{%block title%}Home Page{%endblock title%}

{%block content%}


{%if user.is_authenticated%}   
<form action="{%url 'accounts:logoutView'%}" method="POST"> <!-- this will look throgh url files and finds the path
with the app name accounts and then find logoutView (name attribute) and excute the function-->
{%csrf_token%}
    <button type="submit">LOG OUT</button>
</form>
{%endif%}

{%endblock content%}

polls/templates/polls/listsOfStories.html
{%extends 'base.html'%}
{%block title%}LISTS{%endblock title%}

{%block content%}
<div class="container eamirh">
    <div class="row row-cols-auto">
        {% for story in lists %}
        <div class="col">

            <div class="card" style="width: 18rem;">
{%if story.image%}
<a href="{% url 'polls:story_datail' story.id %}">
   <img src="{{story.image.url}}" class="card-img-top" alt="..."></a>
    {%endif%}
    <div class="card-body">
      <h5 class="card-title">{{ story.title }}</h5>
      <p class="card-text">{{ story.getsnippet }}</p>
      <h6>{{story.author}}</h6>
      <a href="{% url 'polls:story_datail' story.id %}" class="btn btn-primary">Datail Page</a>
    </div>
  </div>
        </div>


{%endfor%}
</div>
</div>
{%endblock content%}

polls/templates/polls/story.html
{% extends 'base.html' %}

{%block title%}
{{storydata.title}}
{%endblock title%}

{%block content%}
<div class="eamirh">

        {% if user in storydata.likes.all %}
        <a href="{% url 'polls:storyunlike' storydata.id %}" style="color: rgb(136, 27, 27);">UNLIKE</a>
        {%else%}
         <a href="{% url 'polls:storylike' storydata.id %}" style="color: green;">LIKE</a><br>
       
    {%endif%}
        <h3>{{storydata.story}}</h3>

    {% if storydata.image%}
    
    
<img src='{{storydata.image.url}}' width="800" height="auto">
    {% endif %}
    
    <p>{{ storydata.date}}</p>
    <h5>{{storydata.author}}</h5>
    </div>

{%endblock content%}

 

polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>vote</title>
</head>
<body>
    <h1>this is what you were looking {{     var     }}</h1>
</body>
</html>